account/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views
from account import views as user_views
app_name = "user_account"

urlpatterns=[
    path('',views.home,name='home'),
    path('register/',views.register, name='register'),
    path('profile/',user_views.profile,name='profile'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),

    # PASSWORD RESET URLS
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='auth/password_reset.html'),name='password_reset')    

]

blog/urls.py
from django.urls import path
from . import views
from .views import *


urlpatterns = [
    path('',PostListView.as_view(),name='home'),
    path('user/<str:username>',UserPostListView.as_view(),name='user-posts'),
    path('post/<int:pk>/',PostDetailView.as_view(),name='post-detail'),
    path('post/<int:pk>/update/',PostUpdateView.as_view(),name='post-update'),
    path('post/<int:pk>/delete/',PostDeleteView.as_view(),name='post-delete'),
    path('post/new/',PostCreateView.as_view(),name='post-create'),
    path('about/',views.about,name='about'),
    

]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('', include('account.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models/post.py
from django.db import models
from django.utils import timezone
from account.models import User 
from myblog.basemodel import TimeBaseModel
from django.urls import reverse


class Post(TimeBaseModel):
    author      = models.ForeignKey(User,on_delete=models.CASCADE)
    title       = models.CharField(max_length=100)
    content     = models.TextField() 
    date_posted = models.DateTimeField(default=timezone.now )

    def __str__(self):
        return self.title 
    
    def get_absolute_url(self):
        return reverse('post-detail',kwargs={'pk':self.pk})

blog/models/profile.py
from django.db import models
from account.models import User
from myblog.basemodel import TimeBaseModel

class Profile(TimeBaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg',upload_to="profile_pics")

    def __str__(self):
        return f'{self.user.username} Profile'
    
    @property
    def imageUrl(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    
    
    

blog/forms.py
from django import forms
from blog.models.profile import Profile
from account.models import User

class UserUpdateForm(forms.ModelForm):
    email= forms.EmailField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'class':'form-control'
            }
        )
    )

    username= forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'class':'form-control'
            }
        )
    )

    class Meta:
        model =User
        fields=['username','email']

class ProfileForm(forms.ModelForm):    
    image = forms.ImageField(
        required=True,
        widget=forms.ClearableFileInput(
            attrs={
                'class':'form-control',
            }
        )
    )
    class Meta:
        model = Profile
        fields = ['image']

blog/views.py
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404
from account.models import User
from blog.models.post import Post
from django.views.generic import (
    ListView,
    DetailView,CreateView,
    UpdateView,DeleteView
)
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin

# Create your views here.
def index(request):

    context = {
        'posts':Post.objects.all()
        }
    return render(request,'blog/home.html',context)

def about(request):
    return render(request, 'blog/about.html',{'title':'about'})


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 4

class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 4

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post



class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title','content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class PostUpdateView(LoginRequiredMixin,UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title','content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False 
    
class PostDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Post
    success_url = '/'
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

templates/blog/about.html
{% extends "blog/base.html" %}

{%block content %}
    <h1>about</h1>
{% endblock content %}

templates/blog/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head> 
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blogs/main.css' %}">
      {% if title%}
    <title>Django Blog - {{title}}</title>
    {% else %}
        <title>Django Blog</title> 

    {%endif%}
    <style> 
        
        .auth{
            margin-left: 750px;
            display: flex;
            color: whitesmoke;
        }
        .navbar{
            background-color: rgb(106, 149, 161);
        }
        a{
            color: whitesmoke;
        }

        .images{
          border-radius: 15cm;
          width: 80px;
          height: 80px;
          margin-top: 10px;
        }
        .media-bodies{
          padding-left: 10px;
        }
    </style>
</head> 
<body>
  <header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home'%}">Django Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home'%}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li> 
          </ul>
          
        </div>
      </div>
      <div class="navbar-nav">
        {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'post-create'%}">New Post</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user_account:logout'%}">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user_account:profile' %}">Profile</a>
              </li> 
        {% else %}
              <div class="auth">
                <!-- <li class="nav-item">
                  <a class="nav-link" href="{% url 'user_account:profile' %}">Profile</a>
                </li> -->
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'user_account:logout'%}">Logout</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'user_account:register' %}">Register</a>
                </li> 
              </div>
        {% endif %}
      </div>
    </nav>
  </header>  
    <div class="container">
        <main role="main" class="container">
            <div class="row">
                <div class="col-md-8">
                  {% if messages %}
                    {% for message in messages %}
                      <div class="alert-{{messages.tags}} ">
                        <h6 style="color: green;">{{message}}</h6>                      </div>
                    {% endfor%}
                  {% endif %}
                    {% block content %}{% endblock %}
                </div>
                <div class="col-md-4">
                    <div class="content-section">
                        <h3>Our Sidebar</h3>
                        <p class="text-muted">You Can Put any information You Like
                            <ul class="list-group">
                                <li class="list-group-item list-group-item-light">Latest Post</li>
                                <li class="list-group-item list-group-item-light">Annoucement</li>
                                <li class="list-group-item list-group-item-light">Calendars</li>
                                <li class="list-group-item list-group-item-light">etc</li>
                            </ul>
                        </p>
                    </div>
                </div>
            </div>
        </main>
    </div>    
  
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/blog/create_profile.html
{% extends "blog/base.html" %}
{%block content%}
<div class="content-section">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-danger">
                <strong>Error!</strong> Please correct the following errors:
                <ul>
                    {% for error in form.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
            <div class="form-group">
                <div class="form-group">
                    <label>Your Username</label>
                    {{form.username}}
                    <i class="icon_mail_alt"></i>   
                </div>
                <div class="form-group">
                    <label>Upload Image</label>
                    {{form.image}} 
                    <i class="icon_lock_alt"></i>
                </div> 
            </div>
    </form>
    <button class="btn btn-outline-info" type="submit">Create</button>

    <div class="clearfix add_bottom_15">
						
        <div class="float-right mt-1"><a class="btn btn-outline-info" href="{% url 'user_account:profile'%}">View Profile</a></div>
    </div>
</div>
{% endblock content %} 

templates/blog/home.html
{% extends  "blog/base.html "%}
{%block content %}
    {% for post in posts%} 
        <article class="media content-section">
            <img src="{{post.author.profile.image.url}}" class="rounded-circle article-img images ">
            <div class="media-body media-bodies">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url "user-posts" post.author.username %}" >{{post.author}}</a>
                    <small class="text-muted">{{post.date_posted|date:"F d,Y"}}</small>
                </div>
                <h2><a class="article-title" href="{% url 'post-detail' post.id%}">{{post.title}}</a></h2>
                <p class="article-content">{{post.content}}</p>
            </div>
        </article>
    {% endfor %} 
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a  class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a  class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %} 
           {% if page_obj.number == num %} 
              <a class="btn btn-info mb-4" href="?page={{ num }}" >{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
              <a class="btn btn-outline-info mb-4" href="?page={{ num }}" >{{num}}</a>
           {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}" class="btn btn-outline-info mb-4">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-info mb-4">Last</a>
        {% endif %}
    {% endif %}
{% endblock content %} 

templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %} 
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are You Sure You Want to delete the Post? "{{object.title}}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>

    </div>

{% endblock content %} 

templates/blog/post_detail.html
{% extends  "blog/base.html "%}
{%block content %}
    <article class="media content-section">
        <img src="{{object.author.profile.image.url}}" class="rounded-circle article-img images alt="">
        <div class="media-body media-bodies">
            <div class="article-metadata">
                <a class="mr-2" href="#" >{{object.author}}</a>
                <small class="text-muted">{{object.date_posted|date:"F d,Y"}}</small>
                {% if object.author == user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.id %}">Update</a>
                    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}">Delete</a>
                </div>
                    {%endif%}
            </div> 
            <h2 class="article-title">{{object.title}}</h2>
            <p class="article-content">{{object.content}}</p>
        </div>
    </article>
{% endblock content %}

templates/blog/post_form.html
{% extends "blog/base.html" %}
{% block content %} 
<style>
    .form-length{
        width: 200px;
    }
</style>

    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post </legend>
            </fieldset>
            <div class="form-group"> 
                <div class="form-group form-length">
                    {{form}} 
                </div>
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>

{% endblock content %} 

templates/blog/profile.html
{% extends "blog/base.html" %}
{% load static %}
{%block content%}
<div class="content-section"> 
    
    <div class="media">
        <img class="rounded-circle account-img images" src="{{user.profile.image.url}}" alt="">
        <div class="media-body">
            <h2 class="account-heading">{{user.username}}</h2>
            <p class="text-secondary">{{user.email}}</p>
        </div>
    </div> 
    <div class="clearfix add_bottom_15">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom  mb-4">Profile Info</legend>
                {{u_form}}
                {{p_form}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update Profile</button>
            </div>
        </form>
						
    </div>
</div>
{% endblock content%}

templates/blog/user_posts.html
{% extends  "blog/base.html "%}
{%block content %}
<h1 class="mb-3">Posts by "{{view.kwargs.username}}" ({{ page_obj.paginator.count}})</h1>
    {% for post in posts%} 
        <article class="media content-section">
            <img src="{{post.author.profile.image.url}}" class="rounded-circle article-img images ">
            <div class="media-body media-bodies">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url "user-posts" post.author.username %}" >{{post.author}}</a>
                    <small class="text-muted">{{post.date_posted|date:"F d,Y"}}</small>
                </div>
                <h2><a class="article-title" href="{% url 'post-detail' post.id%}">{{post.title}}</a></h2>
                <p class="article-content">{{post.content}}</p>
            </div>
        </article>
    {% endfor %} 
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a  class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a  class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %} 
           {% if page_obj.number == num %} 
              <a class="btn btn-info mb-4" href="?page={{ num }}" >{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
              <a class="btn btn-outline-info mb-4" href="?page={{ num }}" >{{num}}</a>
           {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}" class="btn btn-outline-info mb-4">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-info mb-4">Last</a>
        {% endif %}
    {% endif %}
{% endblock content %} 